name: zylu_assignment_frontend
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  flutter_bloc: ^9.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  http: ^1.3.0
  loading_indicator: ^3.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: PoppinsRegular
      fonts:
        - asset: fonts/Poppins-Black.ttf
    - family: PoppinsBold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

